name: Run Weekly AI Bot

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Execute Bot Script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: uv run --with feedparser --with google-genai --with markdown --with python-dotenv python bot.py